[package]
name = "teclado-helena"
version = "1.0.1"
edition = "2024"
build = "build.rs"

[package.metadata.winresource]
ProductName = "Teclado Helena"
FileDescription = "Teclado Helena"
OriginalFilename = "teclado-helena.exe"
CompanyName = "Instituto de Pesquisas Tecnológicas"
LegalCopyright = "Copyright © 2024-2026"

[dependencies]
axum = { version = "0.8.9", features = ["ws"] }
mime_guess = "2.0.4"
rust-embed = "8.2.0"
tokio = { version = "1.35.1", features = ["macros", "net", "rt-multi-thread"] }
qrcode-generator = { version = "6.1.0", default-features = false, features = ["qr"] }
local-ip-address = "0.6.13"
image = { version = "0.25.10", default-features = false, features = ["bmp"] }
enigo = "0.6.1"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.windows-sys]
version = "0.61.2"
features = [
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_System_SystemServices",
    "Win32_UI_WindowsAndMessaging"
]

[build-dependencies]
winresource = "0.1.31"
