name: Java CI with Maven

on:
  push:
    branches: [ "main", "ci-test" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest  

    steps:
    - run: choco install nodejs
    - run: node --version
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: maven
    - name: Build with Maven
      run: mvn install
