name: Rust CI

on:
  push:
    branches: [ "draft/rust-rewrite" ]
  pull_request:
    branches: [ "draft/rust-rewrite" ]

jobs:
  build:

    runs-on: windows-latest  

    steps:
    - run: choco install nodejs
    - run: node --version
    - uses: actions/checkout@v3
    - run: npm install
      working-directory: ./client
    - run: npm run build
      working-directory: ./client
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: binary
        path: target/release/*.exe
