name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest  

    steps:
    - run: choco install nodejs
    - run: node --version
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Install WiX
      run: dotnet tool install --global wix
    - uses: actions/checkout@v3
    - run: npm install
      working-directory: ./client
    - run: npm run build
      working-directory: ./client
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - run: cargo build --release
    - run: wix build ..\..\assets\Package.wxs -o teclado-helena.msi
      working-directory: ./target/release
    - uses: actions/upload-artifact@v4
      with:
        name: binary
        path: target/release/*.exe
    - uses: actions/upload-artifact@v4
      with:
        name: installer
        path: target/release/*.msi
        