name: Rust CI

on:
  push:
    branches: [ "draft/rust-rewrite" ]
  pull_request:
    branches: [ "draft/rust-rewrite" ]

jobs:
  build:

    runs-on: windows-latest  

    steps:
    - run: choco install nodejs
    - run: node --version
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Install WiX
      run: dotnet tool install --global wix
    - uses: actions/checkout@v3
    - run: npm install
      working-directory: ./client
    - run: npm run build
      working-directory: ./client
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - run: cargo build --release
    - run: wix build ..\..\assets\Package.wxs -o teclado-helena.msi
      working-directory: ./target/release
    - uses: actions/upload-artifact@v4
      with:
        name: binary
        path: target/release/*.exe
    - uses: actions/upload-artifact@v4
      with:
        name: installer
        path: target/release/*.msi

    - run: cargo doc
    - run: robocopy target/doc docs/server /s /e
    - run: echo ^<meta http-equiv="refresh" content="0; url=server/teclado_helena/index.html"^> > docs/index.html
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: "./docs"
  
  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2